
Stats for set_toolname <cjnfuncs_testsmtp>:
.toolname         :  cjnfuncs_testsmtp
.main_module      :  <module '__main__' from '/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py'>
.main_full_path   :  /mnt/share/dev/packages/cjnfuncs/tests/demo-smtp.py
.main_dir         :  /mnt/share/dev/packages/cjnfuncs/tests
General user and site paths:
.user_config_dir  :  /home/cjn/.config/cjnfuncs_testsmtp
.user_data_dir    :  /home/cjn/.local/share/cjnfuncs_testsmtp
.user_state_dir   :  /home/cjn/.local/state/cjnfuncs_testsmtp
.user_cache_dir   :  /home/cjn/.cache/cjnfuncs_testsmtp
.user_log_dir     :  /home/cjn/.cache/cjnfuncs_testsmtp/log
.site_config_dir  :  /etc/xdg/cjnfuncs_testsmtp
.site_data_dir    :  /usr/share/cjnfuncs_testsmtp
Based on found user or site dirs:
.env_defined      :  user
.config_dir       :  /home/cjn/.config/cjnfuncs_testsmtp
.data_dir         :  /home/cjn/.local/share/cjnfuncs_testsmtp
.state_dir        :  /home/cjn/.local/state/cjnfuncs_testsmtp
.cache_dir        :  /home/cjn/.cache/cjnfuncs_testsmtp
.log_dir_base     :  /home/cjn/.local/share/cjnfuncs_testsmtp
.log_dir          :  None
.log_file         :  None
.log_full_path    :  __console__

Load config /home/cjn/.config/cjnfuncs_testsmtp/demo_smtp.cfg


=====  Test 1:  body to EmailTo  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <1:  body to EmailTo>
           SMTP.snd_email            -  WARNING:  Email sent <1:  body to EmailTo>


=====  Test 2:  body to EmailTo - not logged  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <2:  body to EmailTo - not logged>
           SMTP.snd_email            -    DEBUG:  Email sent <2:  body to EmailTo - not logged>


=====  Test 3:  filename to EmailTo - not logged  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <3:  filename to EmailTo - not logged>
           SMTP.snd_email            -    DEBUG:  Email sent <3:  filename to EmailTo - not logged>


=====  Test 4:  htmlfile to EmailTo  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <4:  htmlfile to EmailTo>
           SMTP.snd_email            -  WARNING:  Email sent <4:  htmlfile to EmailTo>


=====  Test 5:  body to EmailToMulti  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <5:  body to EmailToMulti>
           SMTP.snd_email            -  WARNING:  Email sent <5:  body to EmailToMulti>


=====  Test 6:  No such file nofile.txt  =====
      demo-smtp.<module>             -    ERROR:  Test failed:  <6:  No such file nofile.txt>
Traceback (most recent call last):
  File "/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py", line 140, in <module>
    snd_email (subj=test_desc, filename="nofile.txt", to="EmailTo", log=True, smtp_config=config)
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 304, in snd_email
    raise SndEmailError (f"snd_email - Message subject <{subj}>:  Failed to load <{xx.full_path}>.\n  {e}") from None
cjnfuncs.core.SndEmailError: snd_email - Message subject <6:  No such file nofile.txt>:  Failed to load </home/cjn/.cache/cjnfuncs_testsmtp/nofile.txt>.
  [Errno 2] No such file or directory: '/home/cjn/.cache/cjnfuncs_testsmtp/nofile.txt'


=====  Test 7:  No to=  =====
      demo-smtp.<module>             -    ERROR:  Test failed:  <7:  No to=>
Traceback (most recent call last):
  File "/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py", line 149, in <module>
    snd_email (subj=test_desc, body="Hello", smtp_config=config)
TypeError: snd_email() missing 1 required positional argument: 'to'


=====  Test 8:  Invalid to=  =====
      demo-smtp.<module>             -    ERROR:  Test failed:  <8:  Invalid to=>
Traceback (most recent call last):
  File "/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py", line 158, in <module>
    snd_email (subj=test_desc, body="Hello", to="me@example.com, junkAtexample.com", log=True, smtp_config=config)
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 320, in snd_email
    To = list_to(to, 'emails', subj, smtp_config=smtp_config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 497, in list_to
    raise SndEmailError (f"Message subject <{subj}>:  <{item}> is not a valid email address")
cjnfuncs.core.SndEmailError: Message subject <8:  Invalid to=>:  <junkAtexample.com> is not a valid email address


=====  Test 9:  This is a test subject - not logged  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <9:  This is a test subject - not logged>
           SMTP.snd_email            -    DEBUG:  Email sent <9:  This is a test subject - not logged>
           SMTP.snd_notif            -    DEBUG:  Notification sent <9:  This is a test subject - not logged> <This is the message body>


=====  Test 10: This is another test subject  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <10: This is another test subject>
           SMTP.snd_email            -    DEBUG:  Email sent <10: This is another test subject>
           SMTP.snd_notif            -  WARNING:  Notification sent <10: This is another test subject> <This is another message body>


=====  Test 11: snd_notif with to='EmailTo'  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <11: snd_notif with to='EmailTo'>
           SMTP.snd_email            -    DEBUG:  Email sent <11: snd_notif with to='EmailTo'>
           SMTP.snd_notif            -  WARNING:  Notification sent <11: snd_notif with to='EmailTo'> <This is another message body>


=====  Test 12: No body, filename, or htmlfile  =====
      demo-smtp.<module>             -    ERROR:  Test failed:  <12: No body, filename, or htmlfile>
Traceback (most recent call last):
  File "/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py", line 194, in <module>
    snd_email (subj=test_desc, to="EmailTo", log=True, smtp_config=config)
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 316, in snd_email
    raise SndEmailError (f"snd_email - Message subject <{subj}>:  No body, filename, or htmlfile specified.")
cjnfuncs.core.SndEmailError: snd_email - Message subject <12: No body, filename, or htmlfile>:  No body, filename, or htmlfile specified.


=====  Test 13: Empty to=  =====
      demo-smtp.<module>             -    ERROR:  Test failed:  <13: Empty to=>
Traceback (most recent call last):
  File "/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py", line 203, in <module>
    snd_email (subj=test_desc, to="", body="Hello", log=True, smtp_config=config)
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 320, in snd_email
    To = list_to(to, 'emails', subj, smtp_config=smtp_config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 497, in list_to
    raise SndEmailError (f"Message subject <{subj}>:  <{item}> is not a valid email address")
cjnfuncs.core.SndEmailError: Message subject <13: Empty to=>:  <> is not a valid email address


=====  Test 14: Invalid to='inval@i^*#d  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <14: Invalid to='inval@i^*#d>
           SMTP.snd_email            -    DEBUG:  Email send try 0 failed.  Retry in <2.0 sec>:
  <{'inval@i^*#d': (553, b'5.1.3 The recipient address <inval@i^*#d> is not a valid RFC 5321 address.\n5.1.3 For more information, go to\n5.1.3  https://support.google.com/a/answer/3221692 and review RFC 5321\n5.1.3 specifications. 5614622812f47-40b322b5900sm1879740b6e.18 - gsmtp')}>
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <14: Invalid to='inval@i^*#d>
           SMTP.snd_email            -    DEBUG:  Email send try 1 failed.  Retry in <2.0 sec>:
  <{'inval@i^*#d': (553, b'5.1.3 The recipient address <inval@i^*#d> is not a valid RFC 5321 address.\n5.1.3 For more information, go to\n5.1.3  https://support.google.com/a/answer/3221692 and review RFC 5321\n5.1.3 specifications. 46e09a7af769-73afaec27aasm1848915a34.0 - gsmtp')}>
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Start TLS
           SMTP.snd_email            -    DEBUG:  Logging into SMTP server
           SMTP.snd_email            -    DEBUG:  Sending message <14: Invalid to='inval@i^*#d>
      demo-smtp.<module>             -    ERROR:  Test failed:  <14: Invalid to='inval@i^*#d>
Traceback (most recent call last):
  File "/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py", line 212, in <module>
    snd_email (subj=test_desc, to="inval@i^*#d", body="Hello", log=True, smtp_config=config)
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 412, in snd_email
    raise SndEmailError (f"snd_email:  Send failed for <{subj}>:\n  <{last_error}>")
cjnfuncs.core.SndEmailError: snd_email:  Send failed for <14: Invalid to='inval@i^*#d>:
  <{'inval@i^*#d': (553, b'5.1.3 The recipient address <inval@i^*#d> is not a valid RFC 5321 address.\n5.1.3 For more information, go to\n5.1.3  https://support.google.com/a/answer/3221692 and review RFC 5321\n5.1.3 specifications. 46e09a7af769-73afb0069f4sm1844998a34.19 - gsmtp')}>


=====  Test 15:  Failed email server  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Email send try 0 failed.  Retry in <2.0 sec>:
  <[Errno -2] Name or service not known>
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Email send try 1 failed.  Retry in <2.0 sec>:
  <[Errno -2] Name or service not known>
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
      demo-smtp.<module>             -    ERROR:  Test failed:  <15:  Failed email server>
Traceback (most recent call last):
  File "/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py", line 222, in <module>
    snd_email (subj=test_desc, to="EmailTo", body="To be, or not to be...", log=True, smtp_config=config)
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 412, in snd_email
    raise SndEmailError (f"snd_email:  Send failed for <{subj}>:\n  <{last_error}>")
cjnfuncs.core.SndEmailError: snd_email:  Send failed for <15:  Failed email server>:
  <[Errno -2] Name or service not known>


=====  Test 16:  Bad server port  =====
      demo-smtp.<module>             -    ERROR:  Test failed:  <16:  Bad server port>
Traceback (most recent call last):
  File "/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py", line 233, in <module>
    snd_email (subj=test_desc, to="EmailTo", body="To be, or not to be...", log=True, smtp_config=config)
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 330, in snd_email
    raise SndEmailError (f"snd_email - Config EmailServerPort <{cfg_port}> is invalid")
cjnfuncs.core.SndEmailError: snd_email - Config EmailServerPort <badport> is invalid


=====  Test 17:  snd_notif Failed email server  =====
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Email send try 0 failed.  Retry in <2.0 sec>:
  <[Errno -2] Name or service not known>
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
           SMTP.snd_email            -    DEBUG:  Email send try 1 failed.  Retry in <2.0 sec>:
  <[Errno -2] Name or service not known>
           SMTP.snd_email            -    DEBUG:  Initialize the SMTP server connection for port <p587tls>
      demo-smtp.<module>             -    ERROR:  Test failed:  <17:  snd_notif Failed email server>
Traceback (most recent call last):
  File "/mnt/share/dev/packages/cjnfuncs/tests/./demo-smtp.py", line 245, in <module>
    snd_notif (subj=test_desc, msg='This is the message body', smtp_config=config)
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 162, in snd_notif
    snd_email (subj=subj, body=msg, to=to, smtp_config=smtp_config)
  File "/mnt/share/dev/packages/cjnfuncs/src/cjnfuncs/SMTP.py", line 412, in snd_email
    raise SndEmailError (f"snd_email:  Send failed for <{subj}>:\n  <{last_error}>")
cjnfuncs.core.SndEmailError: snd_email:  Send failed for <17:  snd_notif Failed email server>:
  <[Errno -2] Name or service not known>


=====  Test 18:  list_to tests  =====
1:   Single email address                ['me@home']
2:   Multiple email addresses            ['me@home', 'you@home', 'me@example.com']
3:   Single number                       ['+14805551212']
3a:  Single number with cc               ['+14805551212']
3b:  Single number int                   ['+14805551212']
4:   Multiple numbers                    ['+14805551212', '+14805551213']
5:   Email-to-SMS addresses              ['4805551212@vzwpix.com', '4805551213@txt.att.net']
6:   Numbers from email addresses        ['+14805551212', '+14805551213']
7:   Other country code                  ['+14805551212', '+4448055512']
Exception:  Message subject <8:   Number too short>:  <480555121> is not a valid phone number
Exception:  Message subject <8a:  Number too long>:  <480222555121> is not a valid phone number
Exception:  Message subject <8b:  Int Number too long>:  <480222555121> is not a valid phone number
Exception:  Message subject <9:   Invalid phone number>:  <480a555121> is not a valid phone number
Exception:  Message subject <10:  No phone number>:  <> is not a valid phone number
Exception:  Message subject <11:  No email address>:  <> is not a valid email address
Exception:  Message subject <12:  Invalid mode>:  <emailsX> is not a valid get_type for list_to()
20:  README example                      ['+14805551212', '+14805551213', '+14805551214', '+44123456']
