2025-06-28 12:28:55,522               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 1 - Built-in print  EXPECT: Pass, return None
2025-06-28 12:28:55,522                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <built-in function print>
  args:         ('Hello', 'there', 'again')
  kwargs:       {'sep': ' blah ', 'end': ' The end.\n'}
2025-06-28 12:28:55,522                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:55,528                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919236
Hello blah there blah again The end.
2025-06-28 12:28:55,529                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:28:55,530                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:28:55,530               demo-rwt.dotest                WARNING:    RETURNED:
None
2025-06-28 12:28:55,530               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 2 - Subprocess ping known  EXPECT: Return subprocess pass result
2025-06-28 12:28:55,530                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f9eb5eca980>
  args:         (['ping', 'yahoo.com', '-c', '1'],)
  kwargs:       {'timeout': 3, 'capture_output': True, 'text': True}
2025-06-28 12:28:55,530                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:55,532                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919238
2025-06-28 12:28:55,949                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:28:55,950                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:28:55,950               demo-rwt.dotest                WARNING:    RETURNED:
CompletedProcess(args=['ping', 'yahoo.com', '-c', '1'], returncode=0, stdout='PING yahoo.com (74.6.231.21) 56(84) bytes of data.\n64 bytes from media-router-fp74.prod.media.vip.ne1.yahoo.com (74.6.231.21): icmp_seq=1 ttl=252 time=73.3 ms\n\n--- yahoo.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 73.298/73.298/73.298/0.000 ms\n', stderr='')
2025-06-28 12:28:55,951               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 3 - Subprocess ping unknown  EXPECT: Return subprocess fail result
2025-06-28 12:28:55,951                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f9eb5eca980>
  args:         (['ping', 'dummyunknown.com', '-c', '1'],)
  kwargs:       {'timeout': 1, 'capture_output': True, 'text': True}
2025-06-28 12:28:55,951                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:55,955                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919260
2025-06-28 12:28:55,985                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:28:55,985                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:28:55,986               demo-rwt.dotest                WARNING:    RETURNED:
CompletedProcess(args=['ping', 'dummyunknown.com', '-c', '1'], returncode=2, stdout='', stderr='ping: dummyunknown.com: Name or service not known\n')
2025-06-28 12:28:55,986               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 4a - Subprocess ping known/unavailable. subprocess timeout < rwt_timeout  EXPECT: Exception subprocess.TimeoutExpired
2025-06-28 12:28:55,986                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f9eb5eca980>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'timeout': 0.5, 'capture_output': True, 'text': True}
2025-06-28 12:28:55,986                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:55,988                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919269
2025-06-28 12:28:56,497                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:28:56,498                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:28:56,498               demo-rwt.dotest                  ERROR:  
  RAISED:     TypeError: TimeoutExpired.__init__() missing 1 required positional argument: 'timeout'
2025-06-28 12:28:56,498               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 4b - Subprocess ping known/unavailable, subprocess timeout < rwt_timeout, rwt_ntries=2  EXPECT: Exception subprocess.TimeoutExpired
2025-06-28 12:28:56,499                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_ntries:   2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f9eb5eca980>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'timeout': 0.5, 'capture_output': True, 'text': True}
2025-06-28 12:28:56,499                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:28:56,499                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:56,504                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919274
2025-06-28 12:28:57,012                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:28:57,012                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:28:57,012                    rwt.run_with_timeout        DEBUG:  T0  - Try 1
2025-06-28 12:28:57,012                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:57,015                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919299
2025-06-28 12:28:57,519                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:28:57,519                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:28:57,520               demo-rwt.dotest                  ERROR:  
  RAISED:     TypeError: TimeoutExpired.__init__() missing 1 required positional argument: 'timeout'
2025-06-28 12:28:57,520               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 4c - Subprocess ping known/unavailable, rwt_timeout < subprocess timeout  EXPECT: Exception TimeoutError
2025-06-28 12:28:57,520                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f9eb5eca980>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'timeout': 3, 'capture_output': True, 'text': True}
2025-06-28 12:28:57,520                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:57,521                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919327
2025-06-28 12:28:58,021                    rwt.run_with_timeout        DEBUG:  T4  - terminate runner_p
2025-06-28 12:28:58,022                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received
2025-06-28 12:28:58,035               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <run> timed out after 0.5 seconds (killed)
2025-06-28 12:28:58,036               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 4d - Subprocess ping known/unavailable, rwt_timeout < subprocess timeout, rwt_ntries=2  EXPECT: Exception TimeoutError
2025-06-28 12:28:58,036                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f9eb5eca980>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'timeout': 3, 'capture_output': True, 'text': True}
2025-06-28 12:28:58,037                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:28:58,037                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:58,043                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919353
2025-06-28 12:28:58,540                    rwt.run_with_timeout        DEBUG:  T4  - terminate runner_p
2025-06-28 12:28:58,541                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received
2025-06-28 12:28:58,552                    rwt.run_with_timeout        DEBUG:  T0  - Try 1
2025-06-28 12:28:58,552                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:58,555                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919380
2025-06-28 12:28:59,055                    rwt.run_with_timeout        DEBUG:  T4  - terminate runner_p
2025-06-28 12:28:59,055                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received
2025-06-28 12:28:59,068               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <run> timed out after 0.5 seconds (killed)
2025-06-28 12:28:59,069               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 4e - Subprocess ping known/unavailable, No subprocess timeout  EXPECT: Exception TimeoutError
2025-06-28 12:28:59,069                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f9eb5eca980>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'capture_output': True, 'text': True}
2025-06-28 12:28:59,069                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:59,074                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919389
2025-06-28 12:28:59,574                    rwt.run_with_timeout        DEBUG:  T4  - terminate runner_p
2025-06-28 12:28:59,574                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received
2025-06-28 12:28:59,587               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <run> timed out after 0.5 seconds (killed)
2025-06-28 12:28:59,587               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 4f - Subprocess ping known/unavailable, No subprocess timeout, rwt_ntries=2  EXPECT: Exception TimeoutError
2025-06-28 12:28:59,587                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f9eb5eca980>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'capture_output': True, 'text': True}
2025-06-28 12:28:59,587                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:28:59,587                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:28:59,591                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919412
2025-06-28 12:29:00,090                    rwt.run_with_timeout        DEBUG:  T4  - terminate runner_p
2025-06-28 12:29:00,091                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received
2025-06-28 12:29:00,102                    rwt.run_with_timeout        DEBUG:  T0  - Try 1
2025-06-28 12:29:00,102                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:00,105                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919438
2025-06-28 12:29:00,604                    rwt.run_with_timeout        DEBUG:  T4  - terminate runner_p
2025-06-28 12:29:00,605                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received
2025-06-28 12:29:00,619               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <run> timed out after 0.5 seconds (killed)
2025-06-28 12:29:00,619               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 6a - Function took too long, killed  EXPECT: Exception TimeoutError, File 'FileNotTouched' not created
2025-06-28 12:29:00,620                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function test_shell_1 at 0x7f9eb5b27880>
  args:         (2, '6a', '/tmp/demo_rwt/FileNotTouched')
  kwargs:       {}
2025-06-28 12:29:00,620                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:00,624                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919464
2025-06-28 12:29:01,123                    rwt.run_with_timeout        DEBUG:  T4  - terminate runner_p
2025-06-28 12:29:01,123                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received
2025-06-28 12:29:01,134               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <test_shell_1> timed out after 0.5 seconds (killed)
2025-06-28 12:29:01,135               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 6b - INFO external log level, Function took too long, not killed  EXPECT: Exception TimeoutError, File 'FileTouched_1' created, message logged during Test 6c
2025-06-28 12:29:01,135                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   1
  rwt_kill:     False
  rwt_debug:    True
  Function:     <function test_shell_1 at 0x7f9eb5b27880>
  args:         (1, '6b', PosixPath('/tmp/demo_rwt/FileTouched_1'))
  kwargs:       {}
2025-06-28 12:29:01,135                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:01,137                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919489
2025-06-28 12:29:01,637               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <test_shell_1> timed out after 0.5 seconds (not killed) orphaned pids: 2919489
2025-06-28 12:29:01,638               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 6c - WARNING external log level, Sleep took too long, rwt_debug=False  EXPECT: Exception TimeoutError, Test 6b INFO log
2025-06-28 12:29:02,138               demo-rwt.test_shell_1             INFO:  Hello there 42.  Log from unkilled Test 6b, pid: 2919489
2025-06-28 12:29:03,143               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <sleep> timed out after 1.5 seconds (killed)
2025-06-28 12:29:03,143               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 6d - Sleep took too long  EXPECT: Exception TimeoutError
2025-06-28 12:29:03,144                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <built-in function sleep>
  args:         (10,)
  kwargs:       {}
2025-06-28 12:29:03,144                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:03,147                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919625
2025-06-28 12:29:03,645                    rwt.run_with_timeout        DEBUG:  T4  - terminate runner_p
2025-06-28 12:29:03,646                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received
2025-06-28 12:29:03,657               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <sleep> timed out after 0.5 seconds (killed)
2025-06-28 12:29:03,657               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 9a - Invalid rwt_timeout  EXPECT: Exception ValueError
2025-06-28 12:29:03,657               demo-rwt.dotest                  ERROR:  
  RAISED:     ValueError: rwt_timeout must be type int or float, received <abc>
2025-06-28 12:29:03,657               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 9b - Invalid rwt_ntries  EXPECT: Exception ValueError
2025-06-28 12:29:03,657               demo-rwt.dotest                  ERROR:  
  RAISED:     ValueError: rwt_ntries must be type int, received <abc>
2025-06-28 12:29:03,657               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 9c - Invalid rwt_kill  EXPECT: Exception ValueError
2025-06-28 12:29:03,657               demo-rwt.dotest                  ERROR:  
  RAISED:     ValueError: rwt_kill must be type bool, received <abc>
2025-06-28 12:29:03,657               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 9d - Invalid rwt_debug  EXPECT: Exception ValueError
2025-06-28 12:29:03,657               demo-rwt.dotest                  ERROR:  
  RAISED:     ValueError: rwt_debug must be type bool, received <abc>
2025-06-28 12:29:03,657               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 11 - Delete non-existing file  EXPECT: Exception FileNotFoundError from function runtime
2025-06-28 12:29:03,657                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <bound method Path.unlink of PosixPath('/tmp/demo_rwt/nosuchfile')>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:03,657                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:03,659                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919651
2025-06-28 12:29:03,661                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:03,662                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:03,662               demo-rwt.dotest                  ERROR:  
  RAISED:     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/demo_rwt/nosuchfile'
2025-06-28 12:29:03,662               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 12 - shutil.copy, rwt_debug True  EXPECT: Pass
2025-06-28 12:29:03,662                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function copy at 0x7f9eb5e13560>
  args:         (PosixPath('/tmp/demo_rwt/t12a'), PosixPath('/tmp/demo_rwt/t12b'))
  kwargs:       {}
2025-06-28 12:29:03,662                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:03,664                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919653
2025-06-28 12:29:03,666                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:03,666                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:29:03,666               demo-rwt.dotest                WARNING:    RETURNED:
/tmp/demo_rwt/t12b
2025-06-28 12:29:03,667               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 13 - shutil.copy, rwt_debug False  EXPECT: Pass
2025-06-28 12:29:03,673               demo-rwt.dotest                WARNING:    RETURNED:
/tmp/demo_rwt/t13b
2025-06-28 12:29:03,673               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 14a - Function wont_terminate, requiring os.kill, rwt_ntries=1  EXPECT: Exception TimeoutError
2025-06-28 12:29:03,673                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function wont_terminate at 0x7f9eb5b27a60>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:03,673                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:03,675                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919657
2025-06-28 12:29:04,175                    rwt.run_with_timeout        DEBUG:  T4  - terminate runner_p
2025-06-28 12:29:04,176                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received
2025-06-28 12:29:04,376                    rwt.run_with_timeout        DEBUG:  T5  - SIGKILL runner_p
2025-06-28 12:29:04,377               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <wont_terminate> timed out after 0.5 seconds (killed)
2025-06-28 12:29:04,377               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 14b - Function wont_terminate, not killed, rwt_ntries=1  EXPECT: Exception TimeoutError, pid listed
2025-06-28 12:29:04,377                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   1
  rwt_kill:     False
  rwt_debug:    True
  Function:     <function wont_terminate at 0x7f9eb5b27a60>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:04,377                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:04,381                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919685
2025-06-28 12:29:04,879               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <wont_terminate> timed out after 0.5 seconds (not killed) orphaned pids: 2919685
2025-06-28 12:29:04,880               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 14c - Function wont_terminate, not killed, rwt_ntries=4  EXPECT: Exception TimeoutError, pids listed
2025-06-28 12:29:04,880                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_ntries:   4
  rwt_kill:     False
  rwt_debug:    True
  Function:     <function wont_terminate at 0x7f9eb5b27a60>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:04,880                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:29:04,880                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:04,883                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919697
2025-06-28 12:29:05,382                    rwt.run_with_timeout        DEBUG:  T0  - Try 1
2025-06-28 12:29:05,383                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:05,388                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919711
2025-06-28 12:29:05,888                    rwt.run_with_timeout        DEBUG:  T0  - Try 2
2025-06-28 12:29:05,888                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:05,893                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919736
2025-06-28 12:29:06,392                    rwt.run_with_timeout        DEBUG:  T0  - Try 3
2025-06-28 12:29:06,393                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,397                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919761
2025-06-28 12:29:06,896               demo-rwt.dotest                  ERROR:  
  RAISED:     TimeoutError: Function <wont_terminate> timed out after 0.5 seconds (not killed) orphaned pids: 2919697 2919711 2919736 2919761
2025-06-28 12:29:06,896               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 16a - WARNING external log level, rwt_ntries=1, rwt_debug=True  EXPECT: Exception FileNotFoundError, Post test logging level:  30
2025-06-28 12:29:06,896                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <bound method Path.unlink of PosixPath('/tmp/demo_rwt/nosuchfile')>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,896                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,898                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919786
2025-06-28 12:29:06,901                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,901                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:06,901               demo-rwt.dotest                  ERROR:  
  RAISED:     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/demo_rwt/nosuchfile'
2025-06-28 12:29:06,901               demo-rwt.<module>              WARNING:  Post test logging level:  30
2025-06-28 12:29:06,902               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 16b - INFO external log level, rwt_ntries=1, rwt_debug=True  EXPECT: Exception FileNotFoundError, Post test logging level:  20
2025-06-28 12:29:06,902                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <bound method Path.unlink of PosixPath('/tmp/demo_rwt/nosuchfile')>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,902                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,904                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919788
2025-06-28 12:29:06,907                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,907                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:06,907               demo-rwt.dotest                  ERROR:  
  RAISED:     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/demo_rwt/nosuchfile'
2025-06-28 12:29:06,907               demo-rwt.<module>              WARNING:  Post test logging level:  20
2025-06-28 12:29:06,907               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 16c - DEBUG external log level, rwt_ntries=1, rwt_debug=True  EXPECT: Exception FileNotFoundError, Post test logging level:  10
2025-06-28 12:29:06,908                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <bound method Path.unlink of PosixPath('/tmp/demo_rwt/nosuchfile')>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,908                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,910                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919790
2025-06-28 12:29:06,914                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,914                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:06,914               demo-rwt.dotest                  ERROR:  
  RAISED:     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/demo_rwt/nosuchfile'
2025-06-28 12:29:06,915               demo-rwt.<module>              WARNING:  Post test logging level:  10
2025-06-28 12:29:06,915               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 16d - DEBUG external log level, rwt_ntries=1, rwt_debug=False  EXPECT: Exception FileNotFoundError, Post test logging level:  10
2025-06-28 12:29:06,920               demo-rwt.dotest                  ERROR:  
  RAISED:     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/demo_rwt/nosuchfile'
2025-06-28 12:29:06,920               demo-rwt.<module>              WARNING:  Post test logging level:  10
2025-06-28 12:29:06,920               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 16e - WARNING external log level, rwt_ntries=2, rwt_debug=True  EXPECT: Exception FileNotFoundError, Post test logging level:  30
2025-06-28 12:29:06,920                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <bound method Path.unlink of PosixPath('/tmp/demo_rwt/nosuchfile')>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,920                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:29:06,921                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,923                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919794
2025-06-28 12:29:06,927                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,927                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:06,928                    rwt.run_with_timeout        DEBUG:  T0  - Try 1
2025-06-28 12:29:06,928                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,930                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919796
2025-06-28 12:29:06,933                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,933                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:06,933               demo-rwt.dotest                  ERROR:  
  RAISED:     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/demo_rwt/nosuchfile'
2025-06-28 12:29:06,933               demo-rwt.<module>              WARNING:  Post test logging level:  30
2025-06-28 12:29:06,933               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 16f - INFO external log level, rwt_ntries=2, rwt_debug=True  EXPECT: Exception FileNotFoundError, Post test logging level:  20
2025-06-28 12:29:06,933                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <bound method Path.unlink of PosixPath('/tmp/demo_rwt/nosuchfile')>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,933                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:29:06,933                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,935                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919798
2025-06-28 12:29:06,938                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,938                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:06,938                    rwt.run_with_timeout        DEBUG:  T0  - Try 1
2025-06-28 12:29:06,938                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,940                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919800
2025-06-28 12:29:06,943                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,944                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:06,944               demo-rwt.dotest                  ERROR:  
  RAISED:     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/demo_rwt/nosuchfile'
2025-06-28 12:29:06,944               demo-rwt.<module>              WARNING:  Post test logging level:  20
2025-06-28 12:29:06,944               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 16g - DEBUG external log level, rwt_ntries=2, rwt_debug=True  EXPECT: Exception FileNotFoundError, Post test logging level:  10
2025-06-28 12:29:06,944                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <bound method Path.unlink of PosixPath('/tmp/demo_rwt/nosuchfile')>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,944                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:29:06,944                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,947                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919802
2025-06-28 12:29:06,950                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,951                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:06,951                    rwt.run_with_timeout        DEBUG:  T0  - Try 1
2025-06-28 12:29:06,951                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,953                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919804
2025-06-28 12:29:06,956                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,956                    rwt.run_with_timeout        DEBUG:  T3  - <exception> msg received from runner_p
2025-06-28 12:29:06,956               demo-rwt.dotest                  ERROR:  
  RAISED:     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/demo_rwt/nosuchfile'
2025-06-28 12:29:06,957               demo-rwt.<module>              WARNING:  Post test logging level:  10
2025-06-28 12:29:06,957               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 16h - DEBUG external log level, rwt_ntries=2, rwt_debug=False  EXPECT: Exception FileNotFoundError, Post test logging level:  10
2025-06-28 12:29:06,967               demo-rwt.dotest                  ERROR:  
  RAISED:     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/demo_rwt/nosuchfile'
2025-06-28 12:29:06,967               demo-rwt.<module>              WARNING:  Post test logging level:  10
2025-06-28 12:29:06,968               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 17a - WARNING external log level, rwt_ntries=1, rwt_debug=True  EXPECT: log_each_level logs WARNING, Post test logging level:  30
2025-06-28 12:29:06,968                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function log_each_level at 0x7f9eb5b279c0>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,968                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,970                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919810
2025-06-28 12:29:06,970               demo-rwt.log_each_level        WARNING:  warning
2025-06-28 12:29:06,972                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,972                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:29:06,972               demo-rwt.dotest                WARNING:    RETURNED:
None
2025-06-28 12:29:06,972               demo-rwt.<module>              WARNING:  Post test logging level:  30
2025-06-28 12:29:06,972               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 17b - INFO external log level, rwt_ntries=1, rwt_debug=True  EXPECT: log_each_level logs WARNING, INFO, Post test logging level:  20
2025-06-28 12:29:06,972                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function log_each_level at 0x7f9eb5b279c0>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,972                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,975                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919812
2025-06-28 12:29:06,975               demo-rwt.log_each_level           INFO:  info
2025-06-28 12:29:06,975               demo-rwt.log_each_level        WARNING:  warning
2025-06-28 12:29:06,977                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,977                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:29:06,977               demo-rwt.dotest                WARNING:    RETURNED:
None
2025-06-28 12:29:06,977               demo-rwt.<module>              WARNING:  Post test logging level:  20
2025-06-28 12:29:06,977               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 17c - DEBUG external log level, rwt_ntries=1, rwt_debug=True  EXPECT: log_each_level logs WARNING, INFO, DEBUG, Post test logging level:  10
2025-06-28 12:29:06,977                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function log_each_level at 0x7f9eb5b279c0>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,978                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,980                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919814
2025-06-28 12:29:06,981               demo-rwt.log_each_level          DEBUG:  debug
2025-06-28 12:29:06,981               demo-rwt.log_each_level           INFO:  info
2025-06-28 12:29:06,981               demo-rwt.log_each_level        WARNING:  warning
2025-06-28 12:29:06,983                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,983                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:29:06,983               demo-rwt.dotest                WARNING:    RETURNED:
None
2025-06-28 12:29:06,983               demo-rwt.<module>              WARNING:  Post test logging level:  10
2025-06-28 12:29:06,983               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 17d - DEBUG external log level, rwt_ntries=1, rwt_debug=False  EXPECT: log_each_level logs WARNING, INFO, DEBUG, Post test logging level:  10
2025-06-28 12:29:06,985               demo-rwt.log_each_level          DEBUG:  debug
2025-06-28 12:29:06,986               demo-rwt.log_each_level           INFO:  info
2025-06-28 12:29:06,986               demo-rwt.log_each_level        WARNING:  warning
2025-06-28 12:29:06,987               demo-rwt.dotest                WARNING:    RETURNED:
None
2025-06-28 12:29:06,987               demo-rwt.<module>              WARNING:  Post test logging level:  10
2025-06-28 12:29:06,987               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 17e - WARNING external log level, rwt_ntries=2, rwt_debug=True  EXPECT: log_each_level logs WARNING, Post test logging level:  30
2025-06-28 12:29:06,987                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function log_each_level at 0x7f9eb5b279c0>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,987                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:29:06,987                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,989                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919818
2025-06-28 12:29:06,990               demo-rwt.log_each_level        WARNING:  warning
2025-06-28 12:29:06,992                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,992                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:29:06,992               demo-rwt.dotest                WARNING:    RETURNED:
None
2025-06-28 12:29:06,992               demo-rwt.<module>              WARNING:  Post test logging level:  30
2025-06-28 12:29:06,992               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 17f - INFO external log level, rwt_ntries=2, rwt_debug=True  EXPECT: log_each_level logs WARNING, INFO, Post test logging level:  20
2025-06-28 12:29:06,992                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function log_each_level at 0x7f9eb5b279c0>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,993                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:29:06,993                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:06,995                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919820
2025-06-28 12:29:06,995               demo-rwt.log_each_level           INFO:  info
2025-06-28 12:29:06,995               demo-rwt.log_each_level        WARNING:  warning
2025-06-28 12:29:06,997                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:06,997                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:29:06,997               demo-rwt.dotest                WARNING:    RETURNED:
None
2025-06-28 12:29:06,997               demo-rwt.<module>              WARNING:  Post test logging level:  20
2025-06-28 12:29:06,997               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 17g - DEBUG external log level, rwt_ntries=2, rwt_debug=True  EXPECT: log_each_level logs WARNING, INFO, DEBUG, Post test logging level:  10
2025-06-28 12:29:06,997                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1.0
  rwt_ntries:   2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function log_each_level at 0x7f9eb5b279c0>
  args:         ()
  kwargs:       {}
2025-06-28 12:29:06,998                    rwt.run_with_timeout        DEBUG:  T0  - Try 0
2025-06-28 12:29:06,998                    rwt.run_with_timeout        DEBUG:  T1  - Starting runner_p
2025-06-28 12:29:07,000                    rwt._runner                 DEBUG:  R1  - runner_p pid 2919822
2025-06-28 12:29:07,000               demo-rwt.log_each_level          DEBUG:  debug
2025-06-28 12:29:07,000               demo-rwt.log_each_level           INFO:  info
2025-06-28 12:29:07,000               demo-rwt.log_each_level        WARNING:  warning
2025-06-28 12:29:07,002                    rwt.run_with_timeout        DEBUG:  T2  - runner_p exited before rwt_timeout
2025-06-28 12:29:07,002                    rwt.run_with_timeout        DEBUG:  T3  - <result> msg received from runner_p
2025-06-28 12:29:07,002               demo-rwt.dotest                WARNING:    RETURNED:
None
2025-06-28 12:29:07,002               demo-rwt.<module>              WARNING:  Post test logging level:  10
2025-06-28 12:29:07,002               demo-rwt.dotest                WARNING:  

==============================================================================================
Test 17h - DEBUG external log level, rwt_ntries=2, rwt_debug=False  EXPECT: log_each_level logs WARNING, INFO, DEBUG, Post test logging level:  10
2025-06-28 12:29:07,005               demo-rwt.log_each_level          DEBUG:  debug
2025-06-28 12:29:07,005               demo-rwt.log_each_level           INFO:  info
2025-06-28 12:29:07,005               demo-rwt.log_each_level        WARNING:  warning
2025-06-28 12:29:07,007               demo-rwt.dotest                WARNING:    RETURNED:
None
2025-06-28 12:29:07,007               demo-rwt.<module>              WARNING:  Post test logging level:  10
