2025-05-04 21:06:57,918  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 1 - test desc - expected result
2025-05-04 21:06:57,918                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_kill:     True
  rwt_debug:    True
  Function:     <built-in function print>
  args:         ('Hello', 'there', 'again')
  kwargs:       {'sep': ' blah ', 'end': ' The end.\n'}
2025-05-04 21:06:57,921                    rwt.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-05-04 21:06:57,923                    rwt._worker                 DEBUG:  W1 - starting runner_p  838355
2025-05-04 21:06:57,925                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838355
2025-05-04 21:06:57,925                    rwt._runner                 DEBUG:  R1 - Starting  838356
Hello blah there blah again The end.
2025-05-04 21:06:57,926                    rwt._worker                 DEBUG:  W4 - runner_to_worker_q msg received  838355
2025-05-04 21:06:57,926                    rwt._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  838355
2025-05-04 21:06:57,927                    rwt._worker                 DEBUG:  W9 - exiting  838355
2025-05-04 21:06:57,928                    rwt.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-05-04 21:06:57,928  demo-run_with_timeout.dotest                WARNING:  RETURNED:
None


2025-05-04 21:06:57,929  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 2 - Subprocess ping known - Return subprocess pass result
2025-05-04 21:06:57,929                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f64229b6ac0>
  args:         (['ping', 'yahoo.com', '-c', '1'],)
  kwargs:       {'timeout': 3, 'capture_output': True, 'text': True}
2025-05-04 21:06:57,929                    rwt.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-05-04 21:06:57,931                    rwt._worker                 DEBUG:  W1 - starting runner_p  838359
2025-05-04 21:06:57,932                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838359
2025-05-04 21:06:57,933                    rwt._runner                 DEBUG:  R1 - Starting  838360
2025-05-04 21:06:58,133                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838359
2025-05-04 21:06:58,133                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838359
2025-05-04 21:06:58,334                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838359
2025-05-04 21:06:58,334                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838359
2025-05-04 21:06:58,405                    rwt._worker                 DEBUG:  W4 - runner_to_worker_q msg received  838359
2025-05-04 21:06:58,405                    rwt._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  838359
2025-05-04 21:06:58,408                    rwt._worker                 DEBUG:  W9 - exiting  838359
2025-05-04 21:06:58,411                    rwt.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-05-04 21:06:58,413  demo-run_with_timeout.dotest                WARNING:  RETURNED:
CompletedProcess(args=['ping', 'yahoo.com', '-c', '1'], returncode=0, stdout='PING yahoo.com (74.6.143.26) 56(84) bytes of data.\n64 bytes from media-router-fp74.prod.media.vip.bf1.yahoo.com (74.6.143.26): icmp_seq=1 ttl=252 time=78.8 ms\n\n--- yahoo.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 78.845/78.845/78.845/0.000 ms\n', stderr='')


2025-05-04 21:06:58,414  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 3 - Subprocess ping unknown - Return subprocess fail result
2025-05-04 21:06:58,414                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f64229b6ac0>
  args:         (['ping', 'dummyunknown.com', '-c', '1'],)
  kwargs:       {'timeout': 1, 'capture_output': True, 'text': True}
2025-05-04 21:06:58,416                    rwt.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-05-04 21:06:58,422                    rwt._worker                 DEBUG:  W1 - starting runner_p  838367
2025-05-04 21:06:58,427                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838367
2025-05-04 21:06:58,430                    rwt._runner                 DEBUG:  R1 - Starting  838368
2025-05-04 21:06:58,490                    rwt._worker                 DEBUG:  W4 - runner_to_worker_q msg received  838367
2025-05-04 21:06:58,491                    rwt._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  838367
2025-05-04 21:06:58,493                    rwt._worker                 DEBUG:  W9 - exiting  838367
2025-05-04 21:06:58,497                    rwt.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-05-04 21:06:58,499  demo-run_with_timeout.dotest                WARNING:  RETURNED:
CompletedProcess(args=['ping', 'dummyunknown.com', '-c', '1'], returncode=2, stdout='', stderr='ping: dummyunknown.com: Name or service not known\n')


2025-05-04 21:06:58,499  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 4 - Subprocess ping known/unavailable - subprocess timeout < rwt_timeout - Exception subprocess.TimeoutExpired
2025-05-04 21:06:58,500                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f64229b6ac0>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'timeout': 0.5, 'capture_output': True, 'text': True}
2025-05-04 21:06:58,501                    rwt.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-05-04 21:06:58,507                    rwt._worker                 DEBUG:  W1 - starting runner_p  838373
2025-05-04 21:06:58,511                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838373
2025-05-04 21:06:58,513                    rwt._runner                 DEBUG:  R1 - Starting  838374
2025-05-04 21:06:58,713                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838373
2025-05-04 21:06:58,713                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838373
2025-05-04 21:06:58,914                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838373
2025-05-04 21:06:58,914                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838373
2025-05-04 21:06:59,025                    rwt._worker                 DEBUG:  W4 - runner_to_worker_q msg received  838373
2025-05-04 21:06:59,026                    rwt._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  838373
2025-05-04 21:06:59,028                    rwt._worker                 DEBUG:  W9 - exiting  838373
2025-05-04 21:06:59,030                    rwt.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-05-04 21:06:59,031  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
TypeError: TimeoutExpired.__init__() missing 1 required positional argument: 'timeout'


2025-05-04 21:06:59,032  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 5 - Subprocess ping known/unavailable - subprocess timeout > rwt_timeout - Exception TimeoutError
2025-05-04 21:06:59,032                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x7f64229b6ac0>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'timeout': 3, 'capture_output': True, 'text': True}
2025-05-04 21:06:59,033                    rwt.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-05-04 21:06:59,038                    rwt._worker                 DEBUG:  W1 - starting runner_p  838382
2025-05-04 21:06:59,041                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838382
2025-05-04 21:06:59,042                    rwt._runner                 DEBUG:  R1 - Starting  838383
2025-05-04 21:06:59,242                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838382
2025-05-04 21:06:59,243                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838382
2025-05-04 21:06:59,443                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838382
2025-05-04 21:06:59,443                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838382
2025-05-04 21:06:59,536                    rwt.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-05-04 21:06:59,537                    rwt.run_with_timeout        DEBUG:  T4 - Killing worker_p
2025-05-04 21:06:59,537                    rwt.worker_int_handler      DEBUG:  WH1 - Signal 15 received  838382
2025-05-04 21:06:59,538                    rwt.worker_int_handler      DEBUG:  WH2 - Sending terminate to runner_p  838382
2025-05-04 21:06:59,538                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received 838383
2025-05-04 21:06:59,642                    rwt.worker_int_handler      DEBUG:  WH4 - runner_p.is_alive? False  838382
2025-05-04 21:06:59,645  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
TimeoutError: Function <run> timed out after 0.5 seconds (killed)


2025-05-04 21:06:59,646  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 6 - Function took too long, killed - Exception TimeoutError, File 'FileNotTouched' not created
2025-05-04 21:06:59,646                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function test_shell_1 at 0x7f64227a00e0>
  args:         (2, 6, '/tmp/cjnfuncs_rwt/FileNotTouched')
  kwargs:       {}
2025-05-04 21:06:59,647                    rwt.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-05-04 21:06:59,654                    rwt._worker                 DEBUG:  W1 - starting runner_p  838390
2025-05-04 21:06:59,659                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838390
2025-05-04 21:06:59,662                    rwt._runner                 DEBUG:  R1 - Starting  838391
2025-05-04 21:06:59,861                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838390
2025-05-04 21:06:59,862                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838390
2025-05-04 21:07:00,062                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838390
2025-05-04 21:07:00,062                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838390
2025-05-04 21:07:00,263                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838390
2025-05-04 21:07:00,263                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838390
2025-05-04 21:07:00,464                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838390
2025-05-04 21:07:00,464                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838390
2025-05-04 21:07:00,652                    rwt.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-05-04 21:07:00,652                    rwt.run_with_timeout        DEBUG:  T4 - Killing worker_p
2025-05-04 21:07:00,652                    rwt.worker_int_handler      DEBUG:  WH1 - Signal 15 received  838390
2025-05-04 21:07:00,652                    rwt.worker_int_handler      DEBUG:  WH2 - Sending terminate to runner_p  838390
2025-05-04 21:07:00,652                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received 838391
2025-05-04 21:07:00,755                    rwt.worker_int_handler      DEBUG:  WH4 - runner_p.is_alive? False  838390
2025-05-04 21:07:00,758  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
TimeoutError: Function <test_shell_1> timed out after 1 seconds (killed)


2025-05-04 21:07:00,759  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 7 - Function took too long, not killed - Exception TimeoutError, File 'FileTouched_1' created
2025-05-04 21:07:01,765  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
TimeoutError: Function <test_shell_1> timed out after 1 seconds (not killed)


2025-05-04 21:07:01,765  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 8 - Sleep took too long - Exception TimeoutError
2025-05-04 21:07:01,766                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <built-in function sleep>
  args:         (10,)
  kwargs:       {}
2025-05-04 21:07:01,767                    rwt.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-05-04 21:07:01,771                    rwt._worker                 DEBUG:  W1 - starting runner_p  838421
2025-05-04 21:07:01,776                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:01,779                    rwt._runner                 DEBUG:  R1 - Starting  838422
2025-05-04 21:07:01,978                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838421
2025-05-04 21:07:01,978                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:02,179                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838421
2025-05-04 21:07:02,179                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:02,379                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838421
2025-05-04 21:07:02,380                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:02,580                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838421
2025-05-04 21:07:02,581                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:02,774  demo-run_with_timeout.test_shell_1          WARNING:  Hello there 42 tnum: 7, pid: 838399
2025-05-04 21:07:02,781                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838421
2025-05-04 21:07:02,781                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:02,982                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838421
2025-05-04 21:07:02,982                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:03,183                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838421
2025-05-04 21:07:03,183                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:03,384                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838421
2025-05-04 21:07:03,384                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:03,584                    rwt._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  838421
2025-05-04 21:07:03,584                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838421
2025-05-04 21:07:03,771                    rwt.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-05-04 21:07:03,772                    rwt.run_with_timeout        DEBUG:  T4 - Killing worker_p
2025-05-04 21:07:03,772                    rwt.worker_int_handler      DEBUG:  WH1 - Signal 15 received  838421
2025-05-04 21:07:03,772                    rwt.worker_int_handler      DEBUG:  WH2 - Sending terminate to runner_p  838421
2025-05-04 21:07:03,773                    rwt.runner_int_handler      DEBUG:  RH1 - Signal 15 received 838422
2025-05-04 21:07:03,875                    rwt.worker_int_handler      DEBUG:  WH4 - runner_p.is_alive? False  838421
2025-05-04 21:07:03,877  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
TimeoutError: Function <sleep> timed out after 2 seconds (killed)


2025-05-04 21:07:03,878  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 9 - Invalid rwt_timeout - Exception ValueError, File 'FileTouched_2' not created
2025-05-04 21:07:03,878  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
ValueError: rwt_timeout must be type int or float, received <abc>


2025-05-04 21:07:03,878  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 10 - Invalid rwt_kill - Exception ValueError, File 'FileTouched_3' not created
2025-05-04 21:07:03,878  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
ValueError: rwt_kill must be type bool, received <abc>


2025-05-04 21:07:03,878  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 11 - Delete non-existing file - Exception FileNotFoundError from function runtime
2025-05-04 21:07:03,878                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <bound method Path.unlink of PosixPath('/tmp/cjnfuncs_rwt/nosuchfile')>
  args:         ()
  kwargs:       {}
2025-05-04 21:07:03,879                    rwt.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-05-04 21:07:03,882                    rwt._worker                 DEBUG:  W1 - starting runner_p  838444
2025-05-04 21:07:03,885                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838444
2025-05-04 21:07:03,887                    rwt._runner                 DEBUG:  R1 - Starting  838445
2025-05-04 21:07:03,891                    rwt._worker                 DEBUG:  W4 - runner_to_worker_q msg received  838444
2025-05-04 21:07:03,891                    rwt._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  838444
2025-05-04 21:07:03,892                    rwt._worker                 DEBUG:  W9 - exiting  838444
2025-05-04 21:07:03,895                    rwt.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-05-04 21:07:03,896  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cjnfuncs_rwt/nosuchfile'


2025-05-04 21:07:03,896  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 12 - shutil.copy, twt_debug True- 
2025-05-04 21:07:03,896                    rwt.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function copy at 0x7f64229076a0>
  args:         (PosixPath('/tmp/cjnfuncs_rwt/t12a'), PosixPath('/tmp/cjnfuncs_rwt/t12b'))
  kwargs:       {}
2025-05-04 21:07:03,897                    rwt.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-05-04 21:07:03,901                    rwt._worker                 DEBUG:  W1 - starting runner_p  838448
2025-05-04 21:07:03,904                    rwt._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  838448
2025-05-04 21:07:03,906                    rwt._runner                 DEBUG:  R1 - Starting  838449
2025-05-04 21:07:03,909                    rwt._worker                 DEBUG:  W4 - runner_to_worker_q msg received  838448
2025-05-04 21:07:03,909                    rwt._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  838448
2025-05-04 21:07:03,910                    rwt._worker                 DEBUG:  W9 - exiting  838448
2025-05-04 21:07:03,912                    rwt.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-05-04 21:07:03,913  demo-run_with_timeout.dotest                WARNING:  RETURNED:
/tmp/cjnfuncs_rwt/t12b


2025-05-04 21:07:03,913  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 13 - shutil.copy, rwt_debug False - 
2025-05-04 21:07:03,928  demo-run_with_timeout.dotest                WARNING:  RETURNED:
/tmp/cjnfuncs_rwt/t13b


